---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: cert_checker


configMapGenerator:
  - name: domains
    files:
      - ./domains

resources:
  - deployment.yaml
